-- ============================================================
-- 搜索广告 schema(docs/05 §3)
-- 在 01_schema.sql 之上扩展;postgres 容器首启按文件名顺序执行(01→02)。
-- 已有库需手动执行本文件,或删除 pgdata 卷后重建。
-- mock 广告复用现有电影 item(ad.item_id → item),零额外向量依赖。
-- ============================================================

-- ---------- 广告主 ----------
CREATE TABLE IF NOT EXISTS advertiser (
    -- 代理主键由 DB 生成(IDENTITY),不再用应用层 MAX+1(有并发竞态 + 全表扫描)。
    -- BY DEFAULT:允许 seed-ads 显式写入确定性 id(随后 setval 把序列推到 MAX+1,见文件末)。
    -- 演进:分库分表 / 多地域写入时,改由应用层用 Snowflake 生成 8 字节有序 id(类型仍 BIGINT,
    --       建表与外键无需改动),去掉对单库序列的依赖。
    advertiser_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT,
    daily_budget  DOUBLE PRECISION,             -- 日预算(元)
    status        TEXT DEFAULT 'active'         -- active / paused / over_budget
);

-- ---------- 广告(创意 + 落地页 + 关联物品) ----------
CREATE TABLE IF NOT EXISTS ad (
    -- 同 advertiser_id:DB 生成(IDENTITY,BY DEFAULT 兼容 seed 显式写入);分片时切 Snowflake,类型不变。
    ad_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advertiser_id BIGINT REFERENCES advertiser(advertiser_id),
    item_id       BIGINT REFERENCES item(item_id),  -- 关联现有 item(复用其 embedding/特征/类目)
    title         TEXT,                             -- 创意标题(教学场景沿用电影标题)
    landing_url   TEXT,
    quality_score DOUBLE PRECISION DEFAULT 1.0,     -- 质量度(相关性/落地页,离线算;M4 先给随机基线)
    status        TEXT DEFAULT 'active',            -- active / paused(投放开关,广告主控制)
    -- 创意审核状态(A2,与投放开关正交):approved / pending_review / rejected。
    -- 默认 approved:seed-ads / 历史广告不带此列即视为已审通过,继续可服务;经 advertiser API 新建的广告走机审→人审。
    review_status TEXT DEFAULT 'approved',
    review_reason TEXT,                             -- 审核意见(拒审原因 / 机审命中项)
    optimization_type TEXT DEFAULT 'CPC',           -- CPC / OCPC(M6):OCPC 用 target_cpa 自动出价
    target_cpa    DOUBLE PRECISION,                 -- oCPC 目标转化成本(元/转化);仅 optimization_type=OCPC 生效
    created_at    TIMESTAMP DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ad_advertiser ON ad (advertiser_id);
CREATE INDEX IF NOT EXISTS idx_ad_item ON ad (item_id);
-- 已有库平滑升级(IF NOT EXISTS 不改既有列)
ALTER TABLE ad ADD COLUMN IF NOT EXISTS optimization_type TEXT DEFAULT 'CPC';
ALTER TABLE ad ADD COLUMN IF NOT EXISTS target_cpa DOUBLE PRECISION;
ALTER TABLE ad ADD COLUMN IF NOT EXISTS review_status TEXT DEFAULT 'approved';
ALTER TABLE ad ADD COLUMN IF NOT EXISTS review_reason TEXT;
-- 智能定向(A3):广告可绑定一个人群包(audience_id);为空=不定向(全体可见)。
-- 人群包由离线 lookalike 作业从种子用户向量扩散生成,物化到 Redis set ad:audience:{id}(在线 SISMEMBER 判定)。
ALTER TABLE ad ADD COLUMN IF NOT EXISTS audience_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_ad_audience ON ad (audience_id);

-- ---------- Look-alike 种子人群(A3):audience_id → 种子 user_id;离线扩散的输入 ----------
CREATE TABLE IF NOT EXISTS ad_audience_seed (
    audience_id BIGINT,
    user_id     BIGINT
);
CREATE INDEX IF NOT EXISTS idx_audience_seed ON ad_audience_seed (audience_id);

-- ---------- 品牌广告 / GD 保量合约(A4):按周期保证曝光量的合约广告 ----------
-- 效果广告走竞价(eCPM+GSP);品牌广告走"合约保量"——在约定周期内保证交付 guaranteed 次曝光。
-- 在线按投放进度分配:落后于时间进度的合约优先出(保量),不落后则让位给竞价广告。
-- 已交付量记 Redis(ad:gd:delivered:{contractId}),曝光时自增;此表存合约元数据。
CREATE TABLE IF NOT EXISTS ad_contract (
    contract_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_id        BIGINT REFERENCES ad(ad_id),
    advertiser_id BIGINT,
    guaranteed   BIGINT,                          -- 合约保证曝光量
    price_cpm    DOUBLE PRECISION DEFAULT 0,       -- 合约 CPM(千次曝光结算,非竞价)
    start_ts     TIMESTAMP,
    end_ts       TIMESTAMP,
    status       TEXT DEFAULT 'active'             -- active / paused / finished
);
CREATE INDEX IF NOT EXISTS idx_ad_contract_status ON ad_contract (status);

-- ---------- 广告创意(DCO 动态创意优化,docs/05 §7 M7:一个广告多套创意,多臂老虎机择优) ----------
CREATE TABLE IF NOT EXISTS ad_creative (
    creative_id BIGSERIAL PRIMARY KEY,
    ad_id       BIGINT REFERENCES ad(ad_id),
    title       TEXT,                              -- 创意标题(教学场景用电影标题的变体)
    landing_url TEXT,
    status      TEXT DEFAULT 'active',             -- active / paused
    review_status TEXT DEFAULT 'approved',         -- 创意级审核(A2):approved / pending_review / rejected;DCO 只展示 approved
    review_reason TEXT,
    created_at  TIMESTAMP DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ad_creative_ad ON ad_creative (ad_id);
ALTER TABLE ad_creative ADD COLUMN IF NOT EXISTS review_status TEXT DEFAULT 'approved';
ALTER TABLE ad_creative ADD COLUMN IF NOT EXISTS review_reason TEXT;

-- ---------- 竞价词(广告主买的关键词 + 匹配类型 + 出价) ----------
CREATE TABLE IF NOT EXISTS bidword (
    id         BIGSERIAL PRIMARY KEY,
    ad_id      BIGINT REFERENCES ad(ad_id),
    keyword    TEXT,
    match_type TEXT,                              -- EXACT / PHRASE / BROAD
    bid        DOUBLE PRECISION,                  -- 出价(CPC,可被 oCPC 覆盖)
    bid_mode   TEXT DEFAULT 'CPC'                 -- CPC / oCPC / oCPM
);
CREATE INDEX IF NOT EXISTS idx_bidword_keyword ON bidword (keyword);  -- 倒排:keyword → ads
-- 按 ad_id 访问的索引:AdvertiserRepository(列/删 WHERE ad_id=?)、AdRepository(WHERE ad_id=ANY(?)、GROUP BY ad_id)
-- 多处按 ad_id 查/聚合,缺此索引则全表扫描。
CREATE INDEX IF NOT EXISTS idx_bidword_ad ON bidword (ad_id);

-- ---------- 广告向量(query 语义匹配用;M4 直接从 item_embedding 拷贝) ----------
CREATE TABLE IF NOT EXISTS ad_embedding (
    ad_id     BIGINT PRIMARY KEY REFERENCES ad(ad_id),
    embedding vector(768),
    model     TEXT
);
-- HNSW 参数同 item_embedding;在线检索须 SET hnsw.ef_search ≥ 最大 LIMIT(见 01_schema.sql 说明)。
CREATE INDEX IF NOT EXISTS idx_ad_embedding_hnsw
    ON ad_embedding USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 200);

-- ---------- 计费 / 曝光日志(广告独有:审计 + 校准 + 结算的源) ----------
CREATE TABLE IF NOT EXISTS ad_event (
    id            BIGSERIAL PRIMARY KEY,
    request_id    TEXT,                           -- 一次搜索请求
    query         TEXT,
    user_id       BIGINT,
    ad_id         BIGINT,
    bidword_id    BIGINT,
    position      INT,                            -- 广告位次(1 基)
    event_type    TEXT,                           -- IMPRESSION / CLICK / CONVERSION
    pctr          DOUBLE PRECISION,               -- 预估 CTR(计费可复核;校准用)
    pctr_calib    DOUBLE PRECISION,               -- 校准后 CTR(进计费的值)
    ecpm          DOUBLE PRECISION,
    charged_price DOUBLE PRECISION,               -- GSP 实际扣费(次高价)
    relevance     DOUBLE PRECISION,               -- query↔ad 相关性(报表/门槛用)
    ad_bucket     TEXT,                           -- 广告分层 A/B 分桶(变体名,如 base / high-reserve)
    ts            TIMESTAMP DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ad_event_req ON ad_event (request_id);
CREATE INDEX IF NOT EXISTS idx_ad_event_type_ts ON ad_event (event_type, ts);
-- 已有库平滑升级(已存在 pgdata 卷不会重跑本文件)
ALTER TABLE ad_event ADD COLUMN IF NOT EXISTS ad_bucket TEXT;
CREATE INDEX IF NOT EXISTS idx_ad_event_ad ON ad_event (ad_id, event_type);
-- DCO:曝光归因到具体创意(供 ad-explore-stats 按创意聚合 CTR 喂多臂老虎机)
ALTER TABLE ad_event ADD COLUMN IF NOT EXISTS creative_id BIGINT;

-- ---------- 已有库平滑升级:把手动赋值的 BIGINT 主键就地改成 IDENTITY(幂等)----------
-- 旧库 advertiser_id/ad_id 是普通 BIGINT(应用层 MAX+1 赋值);这里就地加 IDENTITY,
-- 并把序列推到 MAX+1,之后 recsys-advertiser 改用 INSERT ... RETURNING 由 DB 生成主键,
-- 消除并发竞态与全表扫描。再大体量 / 分片时切 Snowflake(见上方列注释)。
-- attidentity='' 表示该列还不是 IDENTITY;'a'=ALWAYS、'd'=BY DEFAULT。
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_attribute
               WHERE attrelid = 'advertiser'::regclass AND attname = 'advertiser_id' AND attidentity = '') THEN
        ALTER TABLE advertiser ALTER COLUMN advertiser_id ADD GENERATED BY DEFAULT AS IDENTITY;
        PERFORM setval(pg_get_serial_sequence('advertiser', 'advertiser_id'),
                       COALESCE((SELECT MAX(advertiser_id) FROM advertiser), 0) + 1, false);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_attribute
               WHERE attrelid = 'ad'::regclass AND attname = 'ad_id' AND attidentity = '') THEN
        ALTER TABLE ad ALTER COLUMN ad_id ADD GENERATED BY DEFAULT AS IDENTITY;
        PERFORM setval(pg_get_serial_sequence('ad', 'ad_id'),
                       COALESCE((SELECT MAX(ad_id) FROM ad), 0) + 1, false);
    END IF;
END $$;
